"""
Observability: cluster-wide metrics, dashboards and alerting.

    Observability(kubeconfig_path=kc, storage_class="longhorn")

`kube_prometheus_stack` is the only implementation: Prometheus,
Alertmanager and Grafana from one Helm chart
(prometheus-community/kube-prometheus-stack), which also ships
node-exporter and kube-state-metrics so cluster-wide scraping works out of
the box. A second implementation (Victoria Metrics, a Loki-based stack)
is a second driver and one registry entry — no caller changes; see
`multistack/capability.py` for the recipe.

Persistent by default: `REQUIRES = ("cluster", "storage")`, the same as
MinIO. Without a StorageClass, every Prometheus sample and every Grafana
dashboard lives only as long as the pod does, and a routine reschedule
loses both.
"""
from __future__ import annotations

import re
from typing import Any, ClassVar, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from ..capability import CapabilitySpec

SUPPORTED_TYPES = ("kube_prometheus_stack",)

_QUANTITY_RE = re.compile(r"\d+(\.\d+)?(Ei|Pi|Ti|Gi|Mi|Ki|E|P|T|G|M|k)")
_RETENTION_RE = re.compile(r"\d+[smhdwy]")


class KubePrometheusStackOptions(BaseModel):
    """Chart/release settings for the first-party implementation."""

    model_config = ConfigDict(extra="forbid", validate_assignment=True)

    release_name: str = "kube-prometheus-stack"
    chart: str = "kube-prometheus-stack"
    # Grafana's Service type. ClusterIP by default — reach it through
    # `kubectl port-forward` or an ingress_gateway route, not directly
    # from outside the cluster.
    grafana_service_type: str = "ClusterIP"

    @field_validator("release_name", "chart")
    @classmethod
    def _not_empty(cls, value: str, info) -> str:
        if not value:
            raise ValueError(f"{info.field_name} must not be empty")
        return value

    def validate(self) -> None:
        """Kept for `Observability.validate()`, which calls it on the
        options object. Construction already validated; re-running is
        cheap and catches an options model built by other means."""
        self.model_validate(self.model_dump())


# type -> the options class it expects.
OPTIONS_FOR_TYPE = {
    "kube_prometheus_stack": KubePrometheusStackOptions,
}

# Named so the `options` annotation stays stable: a second implementation
# widens this to a Union and nothing else in the file moves.
ObservabilityOptions = KubePrometheusStackOptions


class Observability(CapabilitySpec):
    """
    Declarative definition of cluster observability on an existing
    cluster: metrics, dashboards and alerting.

    `kubeconfig_path` is required; everything else has a working default.
    """

    type: str = "kube_prometheus_stack"
    kubeconfig_path: str

    # None means the chosen implementation's default namespace.
    namespace: Optional[str] = None
    # Pin for reproducibility: unpinned, two runs a month apart can
    # install different chart versions from the same spec.
    chart_version: Optional[str] = None

    # -- persistence ------------------------------------------------------
    # None means "use the cluster's default StorageClass" — the same
    # convention MinIOTenant uses, and the field CapabilityBackend's
    # generic `verify_requirements` reads to check the "storage"
    # dependency (see multistack/capability.py).
    storage_class: Optional[str] = None
    metrics_retention: str = "15d"
    prometheus_volume_size: str = "20Gi"
    grafana_volume_size: str = "5Gi"
    alertmanager_volume_size: str = "2Gi"

    # -- Grafana access -----------------------------------------------------
    # The username is not a secret, so it defaults rather than waiting to
    # be generated. The password is: left None, it is generated by the
    # driver on first install and read back from the live Secret on every
    # later one, so re-running create() never rotates it out from under
    # whoever already has it (see the driver for why that matters).
    grafana_admin_user: str = "admin"
    grafana_admin_password: Optional[str] = None

    # Merged into the rendered Helm values, for anything unmodelled.
    extra_values: Dict[str, Any] = Field(default_factory=dict)

    options: Optional[ObservabilityOptions] = None

    # -- the capability contract (see multistack/capability.py) -----------
    CAPABILITY: ClassVar[str] = "observability"
    # Metrics/dashboards install into a running cluster and need
    # somewhere to persist. Any StorageClass will do, so this depends on
    # the capability, not on one implementation of it.
    REQUIRES: ClassVar[tuple] = ("cluster", "storage")
    FROM_STACK: ClassVar[dict] = {
        "kubeconfig_path": "kubeconfig_path",
        "storage_class": "storage_class",
    }
    # grafana_endpoint() is only meaningful once create() has run, which is
    # why Stack.record() is called after the backend, not before.
    PROVIDES: ClassVar[dict] = {"observability_endpoint": "grafana_endpoint"}
    SUPPORTED_TYPES: ClassVar[tuple] = SUPPORTED_TYPES
    OPTIONS_FOR_TYPE: ClassVar[dict] = OPTIONS_FOR_TYPE
    DEFAULT_NAMESPACES: ClassVar[dict] = {"kube_prometheus_stack": "monitoring"}

    @field_validator("kubeconfig_path")
    @classmethod
    def _kubeconfig_required(cls, value: str) -> str:
        if not value:
            raise ValueError(
                "kubeconfig_path is required — this deploys into an existing "
                "cluster, and the SDK won't fall back to ambient "
                "$KUBECONFIG/~/.kube/config, which can silently target the "
                "wrong cluster."
            )
        return value

    @field_validator("grafana_admin_user")
    @classmethod
    def _admin_user_not_empty(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("grafana_admin_user must not be empty")
        return value

    @field_validator("metrics_retention")
    @classmethod
    def _retention_looks_like_a_duration(cls, value: str) -> str:
        # Prometheus's own format: a number and a unit, e.g. "15d", "6h".
        # A bare number is silently invalid to the chart, not a number of
        # days — better to fail here than watch Prometheus start with the
        # default retention and nobody notice.
        if not _RETENTION_RE.fullmatch(value):
            raise ValueError(
                f"metrics_retention must look like a Prometheus duration "
                f"(e.g. '15d', '6h', '4w'), got {value!r}"
            )
        return value

    @field_validator(
        "prometheus_volume_size", "grafana_volume_size", "alertmanager_volume_size"
    )
    @classmethod
    def _quantity(cls, value: str, info) -> str:
        # A Kubernetes quantity, not a number. "10" is 10 *bytes*, which
        # is a PVC that binds and then immediately fills.
        if not _QUANTITY_RE.fullmatch(value):
            raise ValueError(
                f"{info.field_name} must be a Kubernetes quantity with a "
                f"unit, like '10Gi', got {value!r}. A bare number is bytes."
            )
        return value

    def validate(self) -> None:
        """Checks the spec is coherent before anything reaches a cluster.

        Construction and assignment already ran these checks, so this is a
        re-run rather than the first one. `driver_for()` still calls it,
        and it reads correctly at a call site.
        """
        self.validate_capability()

    def set_grafana_credentials(self, user: str, password: str) -> None:
        """Sets both credentials as one change.

        Used by the driver to record a generated password, or one read
        back from an already-deployed release. A plain assignment works
        too — nothing here requires the two to move together — this just
        keeps every caller consistent with `MinIOTenant.set_credentials`.
        """
        object.__setattr__(self, "grafana_admin_user", user)
        object.__setattr__(self, "grafana_admin_password", password)
        self.validate()

    def _release_name(self) -> str:
        return getattr(self.options, "release_name", None) or self.type

    def _service(self, component: str) -> str:
        """The in-cluster Service name kube-prometheus-stack gives one of
        its components.

        The chart names each Service `<fullname>-<component>`, and
        `<fullname>` collapses to the release name whenever the release is
        named after the chart — true for the default `release_name`. A
        release renamed to something that does not contain "kube-prometheus-stack"
        gets a different fullname from Helm's own naming template, which
        this does not re-implement; override `options.release_name` to
        match what `helm list` actually shows if these stop resolving.
        """
        return f"{self._release_name()}-{component}"

    def grafana_endpoint(self) -> str:
        """In-cluster URL for the Grafana UI.

        This is the value a consumer wants — hand it to an ingress_gateway
        route, or reach it directly from inside the cluster.
        """
        return (
            f"http://{self._service('grafana')}."
            f"{self.resolved_namespace}.svc.cluster.local"
        )

    def prometheus_endpoint(self) -> str:
        """In-cluster URL for the Prometheus query API (PromQL, `/api/v1/*`)."""
        return (
            f"http://{self._service('prometheus')}."
            f"{self.resolved_namespace}.svc.cluster.local:9090"
        )

    def alertmanager_endpoint(self) -> str:
        """In-cluster URL for the Alertmanager API."""
        return (
            f"http://{self._service('alertmanager')}."
            f"{self.resolved_namespace}.svc.cluster.local:9093"
        )
